### PR TITLE
swarp installation for differencing images

### PR DESCRIPTION
**Pull request by scottfdavis**
Previously built Docker images will need to be rebuilt (I believe they must be deleted as well) for this change to take effect.

### CODE REVIEW

**Comment by abostroem** [comment]
@scottfdavis Thanks for the PR. Could you let us know how you tested this PR and how we should test it to verify that its working as expected?

**Comment by scottfdavis** [comment]
> @scottfdavis Thanks for the PR. Could you let us know how you tested this PR and how we should test it to verify that its working as expected?

I tested this with a fresh install of the Docker image and have run all the way through the pipeline including differenced imaging. A more simple, and time efficient, test would be to make sure that swarp is installed correctly after the Docker is rebuilt by confirming it is located in `/usr/bin/swarp` and calling it with `swarp --help`.

**Comment by abostroem** [comment]
@scottfdavis can you please put these commands in the PR so we can make sure everything is in the right place?
"have run all the way through the pipeline including differenced imaging. "

**Comment by scottfdavis** [comment]
Yes. I believe that swarp is needed before the cosmic stage, however, here are the steps I ran up to and including cosmic.

`lscloop.py -n NAME -e TARGDATE -d ID -s ingestsloan`
TARGDATE is a specific date for a science image taken.

`lscloop.py -n NAME -e TEMPDATE --filetype 4 -s psf --show --fwhm 5 --use-sextractor`
TEMPDATE is the data of the template ingested in the previous step. Date ranges are accepted as well.

`lscloop.py -n NAME -e TEMPDATE --filteype 4 -s cosmic`

`lscloop.py -n NAME -e TARGDATE-TARGDATE -s cosmic`

**Comment by crpellegrino** [comment]
I've tried rebuilding the Docker image with the swarp installation steps but I'm getting this error: 
```
Step 10/27 : RUN pip install git+git://github.com/kbarbary/sep.git@master git+git://github.com/dguevel/PyZOGY.git && rm -rf ~/.cache/pip
 ---> Running in 91735afa2dfb
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting git+git://github.com/kbarbary/sep.git@master
  Cloning git://github.com/kbarbary/sep.git (to revision master) to /tmp/pip-req-build-4A4T2U
  Running command git clone -q git://github.com/kbarbary/sep.git /tmp/pip-req-build-4A4T2U
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-_VBRI1/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel oldest-supported-numpy Cython
       cwd: None
  Complete output (9 lines):
  DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
  Collecting setuptools
    Downloading setuptools-44.1.1-py2.py3-none-any.whl (583 kB)
  Collecting wheel
    Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  ERROR: Could not find a version that satisfies the requirement oldest-supported-numpy (from versions: none)
  ERROR: No matching distribution found for oldest-supported-numpy
```
It looks like there's some conflicting versions of numpy between the swarp installation and PyZOGY. Did anyone else have this problem?

**Comment by scottfdavis** [comment]
I did not run into that problem when building the image. Nothing in the docker file that was changed should effect python or related packages.

**Comment by crpellegrino** [comment]
I rebuilt from a fresh directory and it worked. I checked that swarp was installed correctly by running `swarp --help` and checking that `/usr/bin/swarp` exists. Ingesting sloan images seemed to work as well. To test this I ran on an existing image:
```
lscloop.py -n at2016cok -e 20160529 -d 0115 -s ingestsloan
lscloop.py -n at2016cok -e 20160529 --filetype 4 -s psf --show
lscloop.py -n at2016cok -e 20160529 --filetype 4 -s cosmic
```
The SDSS references ingested and visually the image and PSF looked okay. If there are no other steps that use swarp that need to be tested I'll go ahead and merge.

**Pull request merged**
