### PR TITLE
Feature/add targetid selection

### PR DESCRIPTION
**Pull request by abostroem**
This PR adds the ability to select an object based on targetid rather than name, allowing for the processing of all data associated with a single target regardless of what name it was taken under

### CODE REVIEW

**Comment by abostroem** [comment]
@svalenti Can you please provide an example of a test that can be run for this change? I'm not clear if the targetid is the one from my database or the LCO database or the LCO supernova database.

**Comment by svalenti** [comment]
the targetid is the one from the target database, however I can not test it since it seems not vorching as was working before

**Review by dhiramatsu — CHANGES_REQUESTED** [review]
I resolved the filetype conflict in `myloopdef.py`. However, it still doesn't select targets based on thier target IDs. I suppose you need to pass `args.targetid` to `ll = lsc.myloopdef.get_list(...)` in `lscloop.py`.

**Review by dhiramatsu — APPROVED** [review]
I fixed a few typos and tested as @svalenti suggested.

**Pull request merged**
