### PR TITLE
Feature/add apcorr column

### PR DESCRIPTION
**Pull request by abostroem**
**Note: This PR has PR #38 already merged so it could be tested an run on dark**

The aperture correction is currently stored in the sn2 file. This PR adds an aperture correction column (apercorr) to the photlco database which is populated first during the psf stage when the aperture correction is calculated, and then is updated during the psfmag stage when the aperture correction is applied. This update is to ensure that if the sn2 file has changed (e.g. difference imaging normalizing to the template) the aperture correction reflects the actual correction that is applied. 

This PR also includes a script in the trunk/bin directory back_populate_apercorr.py which uses the filepath and filename columns of the photlco table to identify the sn2 file, read the aperture correction, and populate the apercorr keyword. This should be used on any existing database.

Testing (note you'll have to update the path to the catalog):
```
# Run the psf stage on the template
lscloop.py -n 2016cok -e 20180104 -f r -s psf -F --catalog /dark/anaconda/anaconda27/envs/halenv/lib/python2.7/site-packages/lsc/standard/cat/apass/AT2016cok_apass.cat 
# Run the psf stage on the image
lscloop.py -n 2016cok -e 20160529 -f r -s psf -F --catalog /dark/anaconda/anaconda27/envs/halenv/lib/python2.7/site-packages/lsc/standard/cat/apass/AT2016cok_apass.cat 
# Run difference imaging normalizing to template
lscloop.py -n 2016cok -e 20160529 --normalize t -T kb --temptel fl --tempdate 20180104 --fixpix -s diff --difftype 0 -F  -f r --convolve i
#Run the psf stage
lscloop.py -n 2016cok -e 20160529 -s psf --filetype 3 --difftype 0 -F  -f r
```
This should populate the apercorr column for each of these files. Note the aperture correction on the template will be large

```
#run the psfmag stage
lscloop.py -n 2016cok -e 20160529 -s psfmag --filetype 3 --difftype 0 -F  -f r
```
This will update the aperture correction for the image (20160529) to match the template aperture correction

For back populating the apercorr keyword, I changed the epoch variable in the script to be 20160529 and checked that the files associated with that day had an aperture correction and that the ones I had previously processed had not changed.

### CODE REVIEW

**Comment by abostroem** [comment]
Merging this into master results in the following conflict:
```
<<<<<<< HEAD
  `lastunpacked` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
=======
  `lastunpacked` timestamp NULL DEFAULT '1970-01-01 00:00:01',
  `apercorr` float DEFAULT NULL COMMENT 'Aperture correction to correct psfmag to apmag',
>>>>>>> feature/add_apcorr_column
```

Which should be resolved as:

```
  `lastunpacked` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `apercorr` float DEFAULT NULL COMMENT 'Aperture correction to correct psfmag to apmag',
```

**Comment by griffin-h** [comment]
This seems to have broken PyZOGY image subtraction. I get the following error:
```
lscpsf.py /supernova/data/fts/20200724/ogg2m001-fs02-20200724-0085-e91.optimal.SDSS.diff.fits   -r  -t 5.0     -p 6 
FWHM[input]  5 pixels
/supernova/data/fts/20200724/ogg2m001-fs02-20200724-0085-e91.optimal.SDSS.diff.zogypsf 5 5.0 0.30104 200

#### use catalog to measure the psf
################################################################################
warning ron not defined
warning gain not defined
Warning: 728 /supernova/data/fts/20200724/ogg2m001-fs02-20200724-0085-e91.optimal.SDSS.diff.psf.fits

Selecting PSF stars for image /supernova/data/fts/20200724/ogg2m001-fs02-20200724-0085-e91.optimal.SDSS.diff.zogypsf[0]
	1 stars read from file _psf.mag

Star 1 has been added to the PSF star list
	X:  101.00 Y:  100.99  Mag:   6.471  Dmin: -5.363690E-5  Dmax: 0.03150323

Total of 1 PSF stars selected
Traceback (most recent call last):
  File "/supernova/conda-envs/pipeline/bin/lscpsf.py", line 92, in <module>
    catalog, option.datamin, option.datamax, option.show, make_sn2)
  File "/supernova/conda-envs/pipeline/lib/python2.7/site-packages/lsc/lscpsfdef.py", line 496, in ecpsf
    return result, fwhm * scale, aperture_correction
UnboundLocalError: local variable 'aperture_correction' referenced before assignment
```

A quick look through the code tells me this is because `lsc.lscpsfdef.ecpsf` is called with `make_sn2=False` if "optimal" is in the filename (i.e., PyZOGY difference images). The `aperture_correction` is only calculated when `make_sn2=True` but it is returned by `lsc.lscpsfdef.ecpsf` either way.

I don't think we can make the `sn2` file for PyZOGY images, and I don't think we can calculate the aperture correction without making the `sn2` file, so I'm not sure what to do here...

**Comment by crpellegrino** [comment]
I think this is an issue fixed in PR #59 after taking a quick look in the code. In that PR if `make_sn2=False` then the aperture correction is set to 0, but @abostroem can correct me if I'm wrong. We're close to merging that PR in, someone just has to decide the threshold for the PSF stage to fail.

**Comment by griffin-h** [comment]
I just copied those two lines of setting the aperture correction to 0 over to this branch for now, and I'll re-merge it to master.

**Pull request merged**
