### PR TITLE
Fixes to add explict dependencies that are no longer included by default on new M1/M2 macs.

### PR DESCRIPTION
**Pull request by cmccully**

### CODE REVIEW

**Comment by abostroem** [comment]
Visual code review looks reasonable

**Comment by crpellegrino** [comment]
Just a note that the changed version of ds9 is now obsolete (again), here's the most up-to-date link: http://ds9.si.edu/download/debian10/

**Comment by abostroem** [comment]
omg can we talk to someone about this?

**Comment by abostroem** [comment]
I successfully built this on my M2 MacBook Pro - merging

**Pull request merged**
