### PR TITLE
initial commit of manual

### PR DESCRIPTION
**Pull request by abostroem**

### CODE REVIEW

**Comment by abostroem** [comment]
These are in many cases my best guess as what the pipeline is doing and how the analysis should be done. It should be read by someone who knows what they're doing before being merged

**Comment by abostroem** [comment]
This should be merged with the PR #25 as it references the ingestzip.py file added by this PR

**Comment by griffin-h** [comment]
So @abostroem should these be merged or is it superseded by #25?

**Comment by griffin-h** [comment]
I removed the reference to ingestzip.py so we can merge this independently of #25.

**Pull request merged**
