### PR TITLE
Bugfix/filetype not string

### PR DESCRIPTION
**Pull request by abostroem**
In the repo database (we need to check the status of the LCO database) filetype is an integer. This fixes places where the comparison is made to a string.

It also include a trivial change for the word "status" to be printed prior to printing the status

### CODE REVIEW

**Comment by cmccully** [comment]
@abostroem is going to do a grep to search for other instances of this issue.

**Comment by abostroem** [comment]
I grepped trunk/bin and trunk/src/lsc for filetype and found one more string instance which I've fixed and pushed to this branch

**Comment by svalenti** [comment]
I have reviewed these changes and everything should work once the following changes are made:
1) change the type of "filetype" in the supernova database to integer
2) merge this branch to master


to test if the change work just try to select any image with option filetype (for example  lscloop.py -e 20161101-20180130 --filetype 1 --name 2018gj)
after change (1) the pipeline will crash unless this branch is merged in master

**Comment by jfrostburke** [comment]
I made this changes to my local database (the one accessed in docker) and the changes work and return image lists as expected.

One question: I had to update my local database with `alter table photlco modify filetype integer;`, since when I generated it from `supernova.sql` following the instructions in the readme, `filetype` is a text field: 
https://github.com/LCOGT/lcogtsnpipe/blob/ffbad379e20b3817d9679675625e73028a225690/supernova.sql#L705

@abostroem did you generate your local database the same way, or was `filetype` already an integer field in your db? I don't think `supernova.sql` is getting updated in any of the other PRs -- can you update it so it works with this branch on fresh docker installs?

**Comment by abostroem** [comment]
Is this as simple as changing that one line? If so, I can definitely do it. I don't have a great environment to test the docker in - if I make the change can you test it?

**Comment by abostroem** [comment]
I updated supernova.sql to reflect this change. 
# Testing of the supernova.sql file
I created a new branch that I merged this branch and the feature/docker-compose-db branch into. I then ran the following commands in the directory above this repo:
```
socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" &
docker build -t lcogtsnpipe lcogtsnpipe --no-cache
docker-compose -f lcogtsnpipe/docker-compose.yml up
```
Then in a new terminal (still in the directory above this repo):
```
docker exec -it lcosnpipe /bin/bash
sh /lcogtsnpipe/init-db.sh
mysql -D supernova -u supernova -psupernova -h supernovadb
DESCRIBE photlco;
```
Check that 
```
| filetype     | tinyint(4)          | YES  |     | NULL                |                               |
```

I then exited mysql and ingested data to make sure it ran correctly:
```
LCOGTingest.py -n 2016cok -e 2016-05-30 -s 2016-05-28 -f rp --public -r reduced
```
This should add 2 files to the database

**Comment by jfrostburke** [comment]
The database on the sn machine has been updated (with `alter table photlco modify filetype tinyint(4);`), and this PR has been merged and deployed.

**Pull request merged**
