### PR TITLE
adding script to ingest zip files and fits file from a directory

### PR DESCRIPTION
**Pull request by abostroem**
This script is very similar to ingesttar.py. It was written to ingest files that are downloaded from archive.lco.global (specifically the standard star observations)

### CODE REVIEW

**Comment by griffin-h** [comment]
@abostroem I think we should discuss whether this is still useful. Most of the time, external users cannot ingest data from archive.lco.global because they need different credentials. In cases where they can (standard stars, as you mentioned), my opinion is it's easier for them to use LCOGTingest.py (the improved version in #26). Do we want both ways of doing things, or should we defer to the existing script and close this?

**Comment by abostroem** [comment]
I do think the ability to ingest a single fits file, without having to tar it is useful.

**Comment by abostroem** [comment]
I get this error when I try to run LCOGTingest.py
```
LCOGTingest.py --public  -s 20180301 -e 20180330 -S elp -T 1m0a -t STANDARD -x -l 1 -f U
Traceback (most recent call last):
  File "/usr/local/bin/LCOGTingest.py", line 297, in <module>
    start=args.start, end=args.end, OBSTYPE=args.obstype, RLEVEL=rlevel, public=args.public)
  File "/usr/local/bin/LCOGTingest.py", line 37, in get_metadata
    frames = response['results']
KeyError: 'results'
```

**Comment by griffin-h** [comment]
> I do think the ability to ingest a single fits file, without having to tar it is useful.

I see, I didn't realize this script could also just ingest files one at a time from your hard disk. That is potentially useful, although it should also be possible by just running `lsc.mysqldef.ingestredu(filename)`.

**Comment by griffin-h** [comment]
> I get this error when I try to run LCOGTingest.py
> 
> ```
> LCOGTingest.py --public  -s 20180301 -e 20180330 -S elp -T 1m0a -t STANDARD -x -l 1 -f U
> Traceback (most recent call last):
>   File "/usr/local/bin/LCOGTingest.py", line 297, in <module>
>     start=args.start, end=args.end, OBSTYPE=args.obstype, RLEVEL=rlevel, public=args.public)
>   File "/usr/local/bin/LCOGTingest.py", line 37, in get_metadata
>     frames = response['results']
> KeyError: 'results'
> ```

LCOGTingest.py requires a different format for the dates than the rest of the pipeline (YYYY-MM-DD). Let's add this to the documentation.

**Comment by griffin-h** [comment]
After our discussion today, we decided this is unnecessary and possibly undesirable. Closing.

**Pull request closed without merging**
