### PR TITLE
allow --difftype with -b diff

### PR DESCRIPTION
**Pull request by griffin-h**
@abostroem wanted to be able to select images where subtraction failed with a specific image subtraction code (HOTPANTS or PyZOGY). This is my first attempt at making that work.

### CODE REVIEW

**Comment by abostroem** [comment]
This didn't work for:
```
$ lscloop.py -n 2016cok -e 20170104 --id 187 --filetype 3 --difftype 1 -F -s diff --normalize t -T fl --temptel fl --tempdate 20180104 --fixpix --unmask -F
[187]
####################################################################################################
# IMAGE                                    OBJECT           FILTER           WCS             PSF           PSFMAG    APMAG       ZCAT          MAG      ABSCAT

###  total number = 0
lscdiff.py _tar.list _temp.list  -f --normalize t --bgo 3.0 --fixpix  --difftype 1 --suffix .optimal.fl.diff.fits --unmask

##### Error ###
If "_tar.list" is an image, it is corrupted 
 or is not a list of image
```
I rolled back the changes and tried this command again and it identified the file
```
lscloop.py -n 2016cok -e 20170104 --id 187 --filetype 3 --difftype 1 -F -s diff --normalize t -T fl --temptel fl --tempdate 20180104 --fixpix --unmask -F
[187]
####################################################################################################
# IMAGE                                    OBJECT           FILTER           WCS             PSF           PSFMAG    APMAG       ZCAT          MAG      ABSCAT
coj1m011-fl12-20170104-0187-e91.fl.diff	   SN2016cok	        V	      0.0	coj1m011-fl12-20170104-0187-e91.fl.diff.psf	  -2.7332	   -3.394	AT2016cok_apass	  19.1948	        X

###  total number = 1
lscdiff.py _tar.list _temp.list  -f --normalize t --bgo 3.0 --fixpix  --difftype 1 --suffix .optimal.fl.diff.fits --unmask
found name= SN2016cok  targetid= 44
...
```

**Comment by griffin-h** [comment]
Did you mean to write `--filetype 3` in that command? That would imply that you are taking a difference image and subtracting it again. You found a weird edge case where it's not clear whether the `--difftype 1` should refer to the image you're selecting or the subtraction you want it to perform.

**Comment by abostroem** [comment]
< face palm > 
I ran this again without the --filetype flag and I still get the same error
My impression was that if you were using the `-s diff` flag, then the difftype referred to the output and any stage after, it referred to the input - am I missing something?

**Comment by griffin-h** [comment]
That is right about how it used to work, but that is what I had to change in order to implement the feature you want. Now, if `--filetype 3` or if `-b diff`, then `--difftype` and `--temptel` refer to the input. In _addition_ to that, if `-s=diff`, then `--difftype` and `--temptel` refer to the output. I think I fixed the logic for that, so can you try again?

**Comment by abostroem** [comment]
How hard would it be to make this apply to the diff and checkdiff stages?

**Comment by abostroem** [comment]
Tested on:
```
lscloop.py -n 2016cok -e 20160528-20180104 --filetype 3 --difftype 0 -b diff --show
lscloop.py -n 2016cok -e 20160528-20180104 --filetype 3 --difftype 1 -b diff --show
lscloop.py -n 2016cok -e 20160528-20180104 --normalize t -T kb --temptel fl --tempdate 20180104 --fixpix -s diff --difftype 0 -F  -f landolt -b diff
```

and found consistent results with the database (files that were listed did not have rows for diff files in the database)

However, I tried running:
```lscloop.py -n 2016cok -e 20160528-20180104 -s checkdiff --filetype 3 --difftype 0 -b diff --show```

and I ended up with all of the files, I think because in lscloop.py, `filetype` is set to 3 by `-s checkdiff` rather than 1 by the `-b diff` flag so the file that is searched for doesn't exist.

**Comment by griffin-h** [comment]
Sorry I’m not clear what you want to happen for the `-s checkdiff -b diff`
example. That would mean you want to look at all the subtraction triplets
for images where no subtraction has been performed. I could just make it
raise an error if someone runs that command.

**Comment by abostroem** [comment]
you're right - this PR is making me dumb. Approved!

**Review by abostroem — APPROVED** [review]

**Review by crpellegrino — APPROVED** [review]
I tested this by running `lscloop.py -n sn2019ein -e 20190501-20190305 --filetype 3 --difftype 0 -b diff` and `lscloop.py -n sn2019ein -e 20190501-20190305 --filetype 3 --difftype 1 -b diff` and got all the files that don't have an associated subtracted file for that difftype, as expected.

**Pull request merged**
