### PR TITLE
Fix bugs in how aperture correction is applied

### PR DESCRIPTION
**Pull request by abostroem**
This PR does the following:
* Applies the aperture correction to the magnitudes in the sn2 file
* Set threshold for the PSF stage failing and cause it to fail. This is currently set at 0.1 but *should be set to a number acceptable to LCO once PR #52 is merged and the database has been back populated*
* The code exits with an error message when filetype=3 and type=fit and stage=mag (aperture photometry should be sufficient for difference imaging)
* When HOTPANTS is run, look at the aperture correction from the correct, original sn2 file rather than the diff image sn2 file 
* When PyZOGY is run the aperture correction is set to 0

# Testing
### Test that if the aperture correction is too big the PSF will not be calculated:
When run on the master branch, this command should update the PSF column with a filename even though the aperture correction is over 1 magnitude (make sure to replace the catalog with the default apass catalog on your machine)
```
lscloop.py -n 2016cok -e 20180104 -f r -s psf -F --catalog /dark/anaconda/anaconda27/envs/halenv/lib/python2.7/site-packages/lsc/standard/cat/apass/AT2016cok_apass.cat
```
When run in the new branch is run, a message that the aperture correction is too big and that the PSF is not calculated will be printed and the PSF column will be updated with X

### Test the update to the sn2 files
I ran the following command on the master branch and read the sn2 file into an ipython session.
```
lscloop.py -n 2016cok -e 20180104 -f r -s psf -F --id 238
```
```
ipython
from astropy.io import fits
from astropy.io.fits import FITSDiff
ofile = fits.open('../data/lsc/20180104/coj1m011-fl12-20180104-0238-e91.sn2.fits')
```

I switched branches (and re-installed) and ran the same command. I then read the sn2 file into a different variable in the ipython session. 
```
ofile = fits.open('../data/lsc/20180104/coj1m011-fl12-20180104-0238-e91.sn2.fits')
diff = FITSDiff(ofile, ofile2, ignore_fields=('smagf', 'smagerrf'))
print(diff.report())
```
The only differences should be the CHECKSUM keyword and comment and DATASUM comment

```
set(np.round(ofile2[1].data['smagf']-ofile[1].data['smagf'], 3))
```
The set should return 0 and 0.041
```
set(np.round(tbdata2['smagerrf']-np.sqrt(0.024**2 + tbdata['smagerrf']**2), 3))
```
This set should return 0 and 0.001. Inspecting the points that result in 0.001, the I suspect this is a rounding issue resulting from reporting only 3 decimals for both the aperture correction error and the psf magnitude error to 3 decimals.

### Test that PSF photometry is not performed on difference images
The default filetype=1 and type=fit

#### Test that HOTPANTS difference imaging with PSF photometry produces an Exception
```
lscloop.py -n 2016cok -e 20160601-20160701 -f r -s mag --filetype 3 --difftype 0
```
#### Test that PyZOGY difference imaging with PSF photometry produces an Exception
```
lscloop.py -n 2016cok -e 20160601-20160701 -f r -s mag --filetype 3 --difftype 1
```
#### Test that HOTPANTS difference imaging with aperture photometry runs
```
lscloop.py -n 2016cok -e 20160601-20160701 -f r -s mag --filetype 3 --difftype 1 --type ph
```
#### Test that PyZOGY difference imaging with aperture photometry runs
```
lscloop.py -n 2016cok -e 20160601-20160701 -f r -s mag --filetype 3 --difftype 0 --type ph
```
#### Test that non-difference imaging with PSF photometry runs
```
lscloop.py -n 2016cok -e 20160601-20160701 -f r -s mag
```

### Test change in logic about where aperture correction is read from
For testing this branch, I created a new testing branch from the bugfix/apercorr branch and merged in the feature/add_apercorr_column branch so that I could view the aperture correction that were applied in each scenario

#### Test that the original image gets the right aperture correction
```
lscloop.py -n 2016cok -e 20160529 -f r --id 116 -s psf -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 -s psfmag -F
```
Aperture correction between the psf and psfmag stage should be the same (-0.051). This is printed to the screen in an update command at both stages

#### Test merged image has its own aperture correction
```
lscloop.py -n 2016cok -e 20160529 -f r -s merged
lscloop.py -n 2016cok -e 20160529 -f r --filetype 2 -s psf -F
lscloop.py -n 2016cok -e 20160529 -f r --filetype 2 -s psfmag -F
```

#### Test that for the template image the same aperture correction is applied whether the filetype is 1 or 4
```
lscloop.py -n 2016cok -e 20180104 -f r --id 238 -s psf -F
lscloop.py -n 2016cok -e 20180104 -f r --id 238 -s psfmag -F


lscloop.py -n 2016cok -e 20180104 -f r --id 238 -s template
lscloop.py -n 2016cok -e 20180104 -f r --id 238 --filetype 4 -s cosmic -F
lscloop.py -n 2016cok -e 20180104 -f r --id 238 --filetype 4 -s psf -F
lscloop.py -n 2016cok -e 20180104 -f r --id 238 --filetype 4 -s psfmag -F
```
The aperture correction for all psf and psfmag stages should be -0.0412

#### Test that no aperture correction is applied to difference imaging with PyZOGY
```
lscloop.py -n 2016cok -e 20160529 -f r --id 116 -s cosmic -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 -s diff  --normalize t -T kb --temptel fl --tempdate 20180104 --difftype 1 -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 --filetype 3 --difftype 1 -s psf -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 --filetype 3 --difftype 1 -s psfmag -F
```
An aperture correction of 0 should be printed in the UPDATE statements for both the psf and the psfmag stages

Repeat for normalizing to image
```
lscloop.py -n 2016cok -e 20160529 -f r --id 116 -s diff  --normalize i -T kb --temptel fl --tempdate 20180104 --difftype 1 -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 --filetype 3 --difftype 1 -s psf -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 --filetype 3 --difftype 1 -s psfmag -F
```
An aperture correction of 0 should be printed in the UPDATE statements for both the psf and the psfmag stages

#### Test that image aperture correction is applied when the image PSF (`--convolve i`) is used with HOTPANTS
```
lscloop.py -n 2016cok -e 20160529 -f r --id 116 -s diff  --normalize t --convolve i -T kb --temptel fl --tempdate 20180104 --difftype 0 -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 --filetype 3 --difftype 0 -s psf -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 --filetype 3 --difftype 0 -s psfmag -F
```
The aperture correction for the psfmag stage should be -0.051 (matching the image)

Repeat for normalizing to the image
```
lscloop.py -n 2016cok -e 20160529 -f r --id 116 -s diff  --normalize i --convolve i -T kb --temptel fl --tempdate 20180104 --difftype 0 -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 --filetype 3 --difftype 0 -s psf -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 --filetype 3 --difftype 0 -s psfmag -F
```

#### Test that template aperture correction is applied when the template PSF (`--convolve t`) is used with HOTPANTS
```
lscloop.py -n 2016cok -e 20160529 -f r --id 116 -s diff  --normalize t --convolve t -T kb --temptel fl --tempdate 20180104 --difftype 0 -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 --filetype 3 --difftype 0 -s psf -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 --filetype 3 --difftype 0 -s psfmag -F
```
The aperture correction for the psfmag stage should be -0.0412 (matching the image)

Repeat for normalizing to the image
```
lscloop.py -n 2016cok -e 20160529 -f r --id 116 -s diff  --normalize i --convolve t -T kb --temptel fl --tempdate 20180104 --difftype 0 -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 --filetype 3 --difftype 0 -s psf -F
lscloop.py -n 2016cok -e 20160529 -f r --id 116 --filetype 3 --difftype 0 -s psfmag -F
```
The aperture correction for the psfmag stage should be -0.0412 (matching the image)

### CODE REVIEW

**Comment by abostroem** [comment]
I would also note that I couldn't get the pipeline to create a merged file, so this has not been tested on filetype 2 files, although I don't expect anything to fail and I don't think this should stop this PR from being merged

**Comment by abostroem** [comment]
Merging this after PR #52 results in the following conflict:
```
<<<<<<< HEAD
            aperture_correction = np.mean(_dmag)
            lsc.util.updateheader(img + '.sn2.fits', 0, {'APCO': (aperture_correction, 'Aperture correction')})
            lsc.util.updateheader(img + '.sn2.fits', 0, {'APCOERR': (np.std(_dmag), 'Aperture correction error')})
=======
            lsc.util.updateheader(img + '.sn2.fits', 0, {'APCO': (aperture_correction, 'Aperture correction')})
            lsc.util.updateheader(img + '.sn2.fits', 0, {'APCOERR': (aperture_correction_err, 'Aperture correction error')})
>>>>>>> bugfix/apercorr
```
Which should be resolved by keeping the bottom section like this:
```
            lsc.util.updateheader(img + '.sn2.fits', 0, {'APCO': (aperture_correction, 'Aperture correction')})
            lsc.util.updateheader(img + '.sn2.fits', 0, {'APCOERR': (aperture_correction_err, 'Aperture correction error')})
```

**Comment by abostroem** [comment]
I just noticed that the filename was wrong and so the psf column was never set to X. Please check that in addition to printing to the screen the the PSF was not done, that the database has also been set to X

**Comment by abostroem** [comment]
This also fixes a bug in the way the `psf` column was updated when the PSF stage failed and the attempt to apply that to difference imaging. First, there was inconsistency in the code about whether `basename` and `img` contained the `.fits` extension. Additionally, there was an attempt to update the sn2 file and the PSF stage in the difference image if the original PSF was updated. However, due to changes in the way the difference images are named (they include the template's telescope), these files were never found and this row was never updated and the sn2 files were not copied. I decided to remove the difference image part of the code and leave it up to the user to update the difference imaging analysis if the original PSF is changed.

**Comment by abostroem** [comment]
Implications of the bugs that this PR fixes for past data reductions:
* the aperture correction was not applied to the sn2 file. Since this file is used to calculate the zero point, all apparent magnitudes calculated prior to this PR are incorrect by their aperture correction
* when difference imaging was run, the sn2 file for the difference image was a copy of either the sn2 file of the original image or the sn2 file of the template image, determined by the normalization.
    - For HOTPANTS, the aperture correction should correspond to the convolution, not the normalization. Since the aperture correction was read from the sn2 file for the difference image, when the normalization did not match the convolution, the wrong aperture correction was applied to the instrumental magnitude. Since no correction was applied to the sn2 file, this compounds with the error introduced by the previous point.
    - For PyZOGY, the PSF used matches neither the the original image nor the template image and therefore neither aperture correction is appropriate to apply

**Comment by crpellegrino** [comment]
Can you explain why you deleted some SExtractor files in this PR? When trying to do difference imaging using my Dockerized pipeline it fails because it can't find those files.

**Comment by abostroem** [comment]
These files were deleted when I moved the standard directory out of $LCOSNPIPE and into $LCOSNDIR. @cmccully did I move too many files? Should I have just moved the cat directory?

**Comment by abostroem** [comment]
I've added back in the src/lsc/standard files, we can sort out in a different PR if these are needed

**Review by crpellegrino — COMMENTED** [review]
This is a big PR but I think that all the pieces are working as expected.

- I tested that for large aperture corrections, the `-s psf`stage fails as expected.
- For difference imaging, trying to run the `-s mag` stage with the default `--type` produces an error, and running with `--type ph` works as expected
- For non-difference imaging, the `-s mag` stage works with either `--type` input
- The aperture correction between the `-s psf` and `-s psfmag` stages are the same
- The aperture correction is the same whether or not templates are marked as `--filetype 1` or `--filetype 4`
- The aperture correction corresponding to the  `--convolve` flag is the one used during `HOTPANTS` difference imaging

`PYZOGY` wasn't able to run on my machine, so I wasn't able to test any of the aperture corrections using that, although the code looks good. 

The last thing we need to do is figure out the cutoff for the `-s psf` stage to fail. Once we reach a consensus on that, I think this PR is ready to merge.

**Comment by abostroem** [comment]
# Test that default type for filetype 3 is ph and filetype 1 is fit (I don't think the fit matters for filetype 4, since the stages you run on templates don't use the fit)

## filetype=3, no type specified (should be ph by default), difftype=0
### zcat stage
```
lscloop.py -n 2016cok -e 20160530 -f sloan -s zcat --filetype 3 --difftype 0 -F
``` 
I'm not sure how to check what type was used, but this runs

### mag stage
```
lscloop.py -n 2016cok -e 20160530 -f sloan -s mag --filetype 3 --difftype 0 -F
```
This should print: 
`calibratemag.py _tmp.list -s mag -t ph -f sloan -F`
You are specifically looking for `-t ph`

## filetype=3, type=fit, difftype=0
### zcat stage
```
lscloop.py -n 2016cok -e 20160530 -f sloan -s zcat --filetype 3 --difftype 0 -F --type fit
```
I'm not sure how to check what type was used, but this runs

### mag stage
```
lscloop.py -n 2016cok -e 20160530 -f sloan -s mag --filetype 3 --difftype 0 -F --type fit
```
This should print:
```
/dark/anaconda/anaconda27/envs/haltest/bin/lscloop.py:228: UserWarning: Aperture photometry recommended for difference images (--type ph)
  warnings.warn('Aperture photometry recommended for difference images (--type ph)', UserWarning)
calibratemag.py _tmp.list -s mag -t fit -f sloan -F
```
You are specifically looking for a UserWarning being raised and that `-t fit` is present in the calibratemag.py line

## filetype not specified, type not specified
### zcat stage
```
lscloop.py -n 2016cok -e 20160530 -f sloan -s zcat -F
```
I don't know how to test this, but it runs

### mag stage
```
lscloop.py -n 2016cok -e 20160530 -f sloan -s mag
```
This should print:
```
calibratemag.py _tmp.list -s mag -t fit -f sloan -F
```
You are looking for `-t fit`

## filetype not specified, type=ph
### zcat stage
```
lscloop.py -n 2016cok -e 20160530 -f sloan -s zcat --type ph -F
```
I don't know how to test this, but it runs


### mag stage
```
lscloop.py -n 2016cok -e 20160530 -f sloan -s mag --type ph -F
```
This should print:
```
calibratemag.py _tmp.list -s mag -t ph -f sloan -F
```
You are looking for `-t ph`

## filetype=3, no type specified (should be ph by default), difftype=1
### zcat stage
```
lscloop.py -n 2016cok -e 20160530 -f sloan -s zcat --filetype 3 --difftype 1 -F
``` 
I'm not sure how to check what type was used, but this runs

### mag stage
```
lscloop.py -n 2016cok -e 20160530 -f sloan -s mag --filetype 3 --difftype 1 -F
```
This should print: 
`calibratemag.py _tmp.list -s mag -t ph -f sloan -F`
You are specifically looking for `-t ph`

## filetype=3, type=fit, difftype=1
### zcat stage
```
lscloop.py -n 2016cok -e 20160530 -f sloan -s zcat --filetype 3 --difftype 1 -F --type fit
```
I'm not sure how to check what type was used, but this runs

### mag stage
```
lscloop.py -n 2016cok -e 20160530 -f sloan -s mag --filetype 3 --difftype 1 -F --type fit
```
This should print:
```
/dark/anaconda/anaconda27/envs/haltest/bin/lscloop.py:228: UserWarning: Aperture photometry recommended for difference images (--type ph)
  warnings.warn('Aperture photometry recommended for difference images (--type ph)', UserWarning)
calibratemag.py _tmp.list -s mag -t fit -f sloan -F
```
You are specifically looking for a UserWarning being raised and that `-t fit` is present in the calibratemag.py line

# Test use of --max_apercorr flag to change default aperture correction maximum value
```
lscloop.py -n 2016cok -e 20180104 -f r -s psf -F --catalog /dark/hal/lcosn/standard/cat/apass/AT2016cok_apass.cat
```
This should fail because the aperture correction is too big and PSF should be set to 'X'

```
lscloop.py -n 2016cok -e 20180104 -f r -s psf -F --catalog /dark/hal/lcosn/standard/cat/apass/AT2016cok_apass.cat --max_apercorr 2
```
This should work and PSF should be set to the PSF filename

**Comment by crpellegrino** [comment]
I repeated the above tests and for a variety of commands I ran, the default for filetype 3 is ph and for filetype 1 is fit. The --max_apercorr flag also works as expected.

**Pull request merged**
