### PR TITLE
Bugfix/fix ra dec from db

### PR DESCRIPTION
**Pull request by abostroem**
A slight change in logic for when coordinates are read from the database (i.e. `choosepos=False`) and the population of the `goon` variable. @svalenti can elaborate on the reason this change was needed

### CODE REVIEW

**Comment by cmccully** [comment]
@svalenti can you comment more about this?

**Comment by dhiramatsu** [comment]
Pinning @svalenti. Can you also provide a test case that can be run for this change?

**Review by dhiramatsu — COMMENTED** [review]
I tested the PR as suggested by @svalenti and confirmed that it works fine. 
But I would like to suggest printing out a brief instruction (e.g., ''>> Identify target  (mark with "<a> then press <q>")') when running it interactively (with -i), as it wasn't immediately clear to me what I was supposed to or if I was using imexam after seeing "Log file tmp.log open".

**Review by dhiramatsu — APPROVED** [review]
I added a brief instruction for imexam as suggested above.

**Pull request merged**
