### PR TITLE
match instruments by type instead of name

### PR DESCRIPTION
**Pull request by griffin-h**
Currently, when calibrating the local sequence, standard fields are only used from the same individual instrument as the supernova observations. This causes some standards that were observed at the same site on a different instrument of the same type to be left out. Here I change the matching to be by the `instruments.type` column in the database, rather than the `photlco.instrument` column.

### CODE REVIEW

**Comment by abostroem** [comment]
@griffin-h do you have a test example for this PR?

**Comment by griffin-h** [comment]
`lscloop.py -n 'SN 2020cxd' -e 20200201-20200331 --standard all -f landolt -s local -i`

In master, this command will only find two nights of standard stars to calibrate to. In buxfix/match_instruments, it will find three nights. This is because on 2020-03-05, the supernova was observed with 1m0-06/fa07, but the standard field L107 was observed with 1m0-08/fa05.

**Comment by abostroem** [comment]
I’m really struggling to test this PR. Based on the testing example you gave, I thought that L107 and SN2020cxd data from 2020-03-05 in Landolt filters should be sufficient to test this PR.

I downloaded all of the L107 observations for 2020-03-05 and calibrated the B and V filters. The V observations of L107 don’t seem to have an object in them (this seems weird to me because the observations look good, and there are plenty of stars in the frame. I ran checkers and it looked ok to me), so while I get a PSF and a zcat, I don’t get a psfmag. I am able to get 2 instrumental magnitudes for L107 with two different instruments in the B band, but B band observations of 2020cxd don’t seem to have an object in them, so again, I have a psf and a zcat but no psfmag. 



Regardless, based on "the standards need wcs, psf, and zcat. I don’t think the supernova observations need anything except to not be marked as bad.", I thought I should get two objects selected, but I don’t see any even though I can see that they are present in the database. I’m not sure if this is an issue with dark or the PR. 

I can confirm that the "instrument" returned is `Sinistro` when the new query is run on the B band data:
```
SELECT filter, filepath, filename, airmass, shortname, dayobs, type AS instrument,
                                      zcol1, z1, c1, dz1, dc1, zcol2, z2, c2, dz2, dc2, psfmag, psfdmag, apmag, dapmag
                                      FROM photlco LEFT JOIN telescopes ON photlco.telescopeid=telescopes.id
                                      LEFT JOIN instruments ON photlco.instrumentid=instruments.id WHERE 
                                      filename='elp1m006-fa07-20200305-0227-e91.fits' or filename='elp1m006-fa07-20200305-0226-e91.fits'
```

Suggestions welcome

**Comment by abostroem** [comment]
I was able to test this PR by downloading standards for 20200226, 20200305, 20200322 for ELP (all L107). I can confirm that I get the expected output to the test given. @cmccully I think this is ready to merge since @griffin-h tested it on Supernova as he developed it

**Comment by abostroem** [comment]
Fixing conflict now

**Comment by abostroem** [comment]
Conflict resolved and PR retested

**Pull request merged**
