### PR TITLE
changing output format of getmag to be a single mag per line

### PR DESCRIPTION
**Pull request by abostroem**
This PR changes the output of the getmag stage from magnitudes for multiple filters per line to a single filter and magnitude per line to facilitate parsing.

### CODE REVIEW

**Comment by griffin-h** [comment]
I made some changes to simplify the format using Astropy tables. I think it should be okay to merge now, but I'll leave this up to @jfrostburke. In addition to the intended effect of the PR, these changes:
- add column headers to the output (it seems like this was always the intention, but it never worked before)
- add a "magtype" column to the output to differentiate between unsubtracted (magtype=1) and subtracted (magtype=3) images

**Comment by griffin-h** [comment]
I tested this with the command:
`lscloop.py -n 'SN 2017cbv' -e 20170101-20180101 -s getmag --type mag -o foo.txt`

The old output looks like:
```
  2017-03-10 2457822.6880      15.3877       0.0130         9999          0.0         9999          0.0         9999          0.0         9999          0.0         9999          0.0 1m0-05  U
  2017-03-10 2457822.6920      15.3989       0.0122         9999          0.0         9999          0.0         9999          0.0         9999          0.0         9999          0.0 1m0-05  U
  2017-03-10 2457822.6961         9999          0.0      15.9975       0.0074         9999          0.0         9999          0.0         9999          0.0         9999          0.0 1m0-05  B
  2017-03-10 2457822.6988         9999          0.0      15.9769       0.0074         9999          0.0         9999          0.0         9999          0.0         9999          0.0 1m0-05  B
  2017-03-10 2457822.7018         9999          0.0         9999          0.0      15.9349       0.0076         9999          0.0         9999          0.0         9999          0.0 1m0-05  V
  2017-03-10 2457822.7036         9999          0.0         9999          0.0      15.9005       0.0076         9999          0.0         9999          0.0         9999          0.0 1m0-05  V
  2017-03-10 2457822.7056         9999          0.0         9999          0.0         9999          0.0      15.8695       0.0059         9999          0.0         9999          0.0 1m0-05  g
  2017-03-10 2457822.7084         9999          0.0         9999          0.0         9999          0.0      15.8724       0.0067         9999          0.0         9999          0.0 1m0-05  g
  2017-03-10 2457822.7113         9999          0.0         9999          0.0         9999          0.0         9999          0.0      15.8854       0.0071         9999          0.0 1m0-05  r
  2017-03-10 2457822.7132         9999          0.0         9999          0.0         9999          0.0         9999          0.0      15.8861       0.0080         9999          0.0 1m0-05  r
```
The old output, after processing with my old script, looks like this:
```
  2017-03-10 2457822.6880      15.3877       0.0130 1m0-05  U
  2017-03-10 2457822.6920      15.3989       0.0122 1m0-05  U
  2017-03-10 2457822.6961      15.9975       0.0074 1m0-05  B
  2017-03-10 2457822.6988      15.9769       0.0074 1m0-05  B
  2017-03-10 2457822.7018      15.9349       0.0076 1m0-05  V
  2017-03-10 2457822.7036      15.9005       0.0076 1m0-05  V
  2017-03-10 2457822.7056      15.8695       0.0059 1m0-05  g
  2017-03-10 2457822.7084      15.8724       0.0067 1m0-05  g
  2017-03-10 2457822.7113      15.8854       0.0071 1m0-05  r
  2017-03-10 2457822.7132      15.8861       0.0080 1m0-05  r
```
The new output looks like this:
```
dateobs jd mag dmag telescope filter magtype
2017-03-10 2457822.68803 15.3877 0.0130 1m0-05 U 3
2017-03-10 2457822.69197 15.3989 0.0122 1m0-05 U 3
2017-03-10 2457822.69605 15.9975 0.0074 1m0-05 B 3
2017-03-10 2457822.69883 15.9769 0.0074 1m0-05 B 3
2017-03-10 2457822.70175 15.9349 0.0076 1m0-05 V 3
2017-03-10 2457822.70361 15.9005 0.0076 1m0-05 V 3
2017-03-10 2457822.70564 15.8695 0.0059 1m0-05 g 3
2017-03-10 2457822.70842 15.8724 0.0067 1m0-05 g 3
2017-03-10 2457822.71134 15.8854 0.0071 1m0-05 r 3
```

**Comment by jfrostburke** [comment]
Tested and works as expected. I've updated my script in #31 to be compatible with the new `getmag` output (in addition to the old output, and the old procphot'ed output).

**Comment by jfrostburke** [comment]
PS Yay astropy tables

**Pull request merged**
