### PR TITLE
Add option to use reproject instead of gregister for image alignment

### PR DESCRIPTION
**Pull request by griffin-h**
@arcavi and I have both reported problems with `iraf.immatch.gregister` not aligning images correctly prior to subtraction. This might be due to temporary files...I haven't looked into it. However it was fairly easy to replace gregister with the pure-Python `reproject.reproject_interp` function associated with Astropy. This avoids the step of having to calculate the transformation, save it in a temporary file (`tmpcoo`), and then apply it to the images. I attached this to the existing `--no_iraf` option (although IRAF is still used for `fixpix`).

Possible downsides:
- adds a new dependency (`reproject`), but it's pip/conda installable
- `--show` no longer works to show the image alignment in real time, but I'm not sure if anyone used this anyway

### CODE REVIEW

**Comment by griffin-h** [comment]
I need to add some documentation to the manual.

**Comment by jfrostburke** [comment]
Apologies for the long delay, I'm just testing this now and it is not working for me. I ran this command to test that image subtraction was working in my docker install and it went smoothly and produced a difference image:

`lscloop.py -n SN2020hvf -e 20200421 -f g -T fa --normalize t --tempdate 20200425 --temptel fa --difftype 1 -s diff -F`

(This was after generating PSFs and running the cosmic stage on both the template and science images, required for `-s diff` to work.)

When I run the same command with `--no_iraf` it can't find the variance image for the template and crashes. In `lscdiff.py` there is some code to deal with when there's not a variance image (line 264), so maybe one solution is to make that a function and call it in this case, but I don't know if that's the appropriate thing to do.

Here's the full traceback of the crash, for posterity:

```
supernova@3054ead3db60:~$ lscloop.py -n SN2020hvf -e 20200421 -f g -T fa --normalize t --tempdate 20200425 --temptel fa --difftype 1 -s diff -F --no_iraf
Attempting to run on too many cores, reducing to 3
['gp', 'SDSS-G']
####################################################################################################
# IMAGE                                    OBJECT           FILTER           WCS             PSF           PSFMAG    APMAG       ZCAT          MAG      ABSCAT
elp1m008-fa05-20200421-0263-e91	   at2020hvf	       gp	      0.0	elp1m008-fa05-20200421-0263-e91.psf	   9999.0	   9999.0	at2020hvf_sloan	   9999.0	        X

###  total number = 1
['gp', 'SDSS-G']
lscdiff.py _tar.list _temp.list  -f --normalize t --bgo 3.0 --difftype 1 --suffix .optimal.fa.diff.fits --no-iraf
found name= at2020hvf  targetid= 7
found name= SN2020hvf  targetid= 7
/usr/local/lib/python2.7/site-packages/reproject/interpolation/core_celestial.py:26: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(array.dtype, np.float):
/usr/local/bin/lscdiff.py:190: RuntimeWarning: invalid value encountered in greater
  tempmask_reproj = (tempmask_reproj > 0.) | (temp_foot == 0.)
Traceback (most recent call last):
  File "/usr/local/bin/lscdiff.py", line 193, in <module>
    tempnoise_reproj, tempnoise_foot = reproject_interp(_dirtemp + tempnoise0, head_targ)
  File "/usr/local/lib/python2.7/site-packages/reproject/interpolation/high_level.py", line 92, in reproject_interp
    array_in, wcs_in = parse_input_data(input_data, hdu_in=hdu_in)
  File "/usr/local/lib/python2.7/site-packages/reproject/utils.py", line 16, in parse_input_data
    return parse_input_data(fits.open(input_data), hdu_in=hdu_in)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 148, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 402, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1006, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/usr/local/lib/python2.7/site-packages/astropy/utils/decorators.py", line 539, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/util.py", line 395, in fileobj_open
    return open(filename, mode)
IOError: [Errno 2] No such file or directory: '/supernova/data/lsc/20200425/coj1m003-fa19-20200425-0210-e91.temp.var.fits'
```

**Comment by griffin-h** [comment]
Thanks @jfrostburke, you made this very easy to debug. I think all we need to do is prevent it from crashing at line 193 if there is no mask, and let the code at line 264 (which runs for IRAF and no-IRAF) take care of it. I pushed that change now.

**Comment by jfrostburke** [comment]
There were minor merge conflicts with master (from the PR which emails sne@lco.global when things are different sizes). I resolved those and tested with the new changes and difference imaging was successful. Merged and deployed.

**Pull request merged**
