### PR TITLE
Modify status logic in checkpsf stage

### PR DESCRIPTION
**Pull request by abostroem**
The checkpsf stage was trying to run on images for which PSF='X' due to an error in logic. This fixes that.

### CODE REVIEW

**Comment by abostroem** [comment]
# Testing:
Identified a file for which the PSF='X' and ran the command:
```
lscloop.py -n "SN 2016cok" -e 20160605 -s checkpsf --show -f V
['V', 'Bessell-V']
####################################################################################################
# IMAGE                                    OBJECT           FILTER           WCS             PSF           PSFMAG    APMAG       ZCAT          MAG      ABSCAT
cpt1m013-kb76-20160605-0105-e91	   SN2016cok	        V	      0.0	        X	   9999.0	   9999.0	AT2016cok_apass	   9999.0	        X
cpt1m013-kb76-20160605-0106-e91	   SN2016cok	        V	      0.0	        X	   9999.0	   9999.0	AT2016cok_apass	   9999.0	        X

###  total number = 2
cpt1m013-kb76-20160605-0105-e91.fits -1
status -1: sn2.fits file not found
cpt1m013-kb76-20160605-0106-e91.fits -1
status -1: sn2.fits file not found
```

Previously this would result in a status of 1 and an error when the code tried to open the non-existent sn2 file. This same command should be run on a file for which the PSF stage was successful.

**Comment by crpellegrino** [comment]
I tested this on a file where the PSF stage ran successfully and it worked as expected. However, when I tried running it on a file with PSF = 'X" I got this: 
```
lscloop.py -n sn2019ein -e 20190503 -f g -s checkpsf --show
Attempting to run on too many cores, reducing to 7
['gp', 'SDSS-G']
####################################################################################################
# IMAGE                                    OBJECT           FILTER           WCS             PSF           PSFMAG    APMAG       ZCAT          MAG      ABSCAT
elp1m008-fa05-20190503-0180-e91	   SN2019ein	       gp	      0.0	        X	   9999.0	   9999.0	at2019ein_apass	   9999.0	        X

###  total number = 1
elp1m008-fa05-20190503-0180-e91.fits 0
status 0: WCS stage not done
```

I tried fixing this by rerunning the wcs stage and then the checkpsf stage again, but I still got the same error. I'm not sure why this is happening, but I don't think this is the expected response.

**Comment by abostroem** [comment]
I saw this issue but didn't think it was that big a deal. The Status=0 means the previous stage is not done. In this case, the previous stage is the PSF stage - which its true - hasn't been done or was done and failed. Do you think we should change line 918 in myloopdef.py to say PSF stage not done rather than WCS stage not done? Especially given that the WCS stage has almost always been done by Banzai?

**Comment by crpellegrino** [comment]
Oh I see, that makes total sense. In that case then yeah, I'd say it probably makes sense to change "WCS stage not done" to "PSF stage not done" for clarity.

**Comment by crpellegrino** [comment]
I tested this on images with PSFs, which displayed the PSFs as expected: 
```
lscloop.py -n sn2019ein -e 20190501 -f g -s checkpsf
Attempting to run on too many cores, reducing to 7
['gp', 'SDSS-G']
####################################################################################################
# IMAGE                                    OBJECT           FILTER           WCS             PSF           PSFMAG    APMAG       ZCAT          MAG      ABSCAT
elp1m008-fa05-20190501-0141-e91	   at2019ein	       gp	      0.0	elp1m008-fa05-20190501-0141-e91.psf	   9999.0	   9999.0	        X	   9999.0	        X
elp1m008-fa05-20190501-0142-e91	   at2019ein	       gp	      0.0	elp1m008-fa05-20190501-0142-e91.psf	   9999.0	   9999.0	        X	   9999.0	        X

###  total number = 2
elp1m008-fa05-20190501-0141-e91.fits 1
>>>good psf [[y]/n] or [b] bad quality ? 
elp1m008-fa05-20190501-0142-e91.fits 1
>>>good psf [[y]/n] or [b] bad quality ? 
```
On a file where PSF='X", it returns a status code of 0: 
```
lscloop.py -n sn2019ein -e 20190503 -f g -s checkpsf
Attempting to run on too many cores, reducing to 7
['gp', 'SDSS-G']
####################################################################################################
# IMAGE                                    OBJECT           FILTER           WCS             PSF           PSFMAG    APMAG       ZCAT          MAG      ABSCAT
elp1m008-fa05-20190503-0180-e91	   SN2019ein	       gp	      0.0	        X	   9999.0	   9999.0	at2019ein_apass	   9999.0	        X

###  total number = 1
elp1m008-fa05-20190503-0180-e91.fits 0
status 0: PSF stage not done
```
Everything seems to work fine, so I'll merge and deploy.

**Pull request merged**
