### PR TITLE
avoid downloading guider images

### PR DESCRIPTION
**Pull request by griffin-h**
Guider images from the OGG_calib and COJ_calib proposals are currently being downloaded (although they are not ingested into the database). This PR should avoid finding them at all by specifying that only images from the spectrographs (en05, en06, en12) should be downloaded and ingested.

### CODE REVIEW

**Comment by dhiramatsu** [comment]
This is likely unnecessary, but just to make sure: don't you also want to specify the spectrographs when adding links to FLOYDS guider frames in database with `RLEVEL=90`?

**Comment by dhiramatsu** [comment]
Looks good to me. Do you have any specific test cases that you want me to run?

**Comment by griffin-h** [comment]
> Looks good to me. Do you have any specific test cases that you want me to run?

I think the only thing to test is just running the ingestion (`ingestall.py`) and checking whether it gets the files you want (and only the files you want).

**Review by dhiramatsu — APPROVED** [review]
Tested fine in the docker

**Pull request merged**
